import pandas as pd

df = pd.read_csv("Electric_Vehicle_Population_Data.csv")

print("Total rows:", len(df))

print(df[['Model Year', 'Make', 'Model', 'Electric Vehicle Type', 'Electric Range', 'Base MSRP', 'State']].head(10))
print("\nTop 10 EV Brands:")
print(df['Make'].value_counts().head(10))
print("\nEV Registrations by Year:")
print(df['Model Year'].value_counts().sort_index())
import matplotlib.pyplot as plt

yearly = df['Model Year'].value_counts().sort_index()

plt.figure(figsize=(12, 6))
plt.plot(yearly.index, yearly.values, color='steelblue', linewidth=2.5, marker='o')
plt.title('EV Adoption Growth Over the Years', fontsize=16)
plt.xlabel('Year')
plt.ylabel('Number of EVs Registered')
plt.grid(True)
plt.tight_layout()
plt.savefig('ev_growth.png')
plt.show()
plt.figure(figsize=(12, 6))
top_brands = df['Make'].value_counts().head(10)
plt.bar(top_brands.index, top_brands.values, color='steelblue')
plt.title('Top 10 EV Brands in the US', fontsize=16)
plt.xlabel('Brand')
plt.ylabel('Number of EVs')
plt.tight_layout()
plt.savefig('top_brands.png')
plt.show()
plt.figure(figsize=(8, 8))
ev_types = df['Electric Vehicle Type'].value_counts()
plt.pie(ev_types.values, labels=ev_types.index, autopct='%1.1f%%', colors=['steelblue', 'orange'])
plt.title('BEV vs PHEV — Which EV Type Do People Buy?', fontsize=14)
plt.tight_layout()
plt.savefig('ev_types.png')
plt.show()
avg_range = df[df['Electric Range'] > 0].groupby('Model Year')['Electric Range'].mean()

plt.figure(figsize=(12, 6))
plt.plot(avg_range.index, avg_range.values, color='green', linewidth=2.5, marker='o')
plt.title('Average EV Range Improvement Over the Years', fontsize=16)
plt.xlabel('Year')
plt.ylabel('Average Range (miles)')
plt.grid(True)
plt.tight_layout()
plt.savefig('ev_range.png')
plt.show()